# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Journal of a Reluctant Web Developer
email: 
description: >- # this means to ignore newlines until "baseurl:"
  Notes and questions from the often confusing (but sometimes pretty neat) 
  wide world of full stack web development.
  Mostly a place to help me remember the many things I've researched or 
  needed to learn.
  Mainly (so far): C#, .NET, Angular, security (OAuth, OIDC), etc.
baseurl: "/joarwd" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  plclark11

# Build settings
markdown: kramdown
theme: minima
plugins:
  

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
